# Generated by Django 4.2.16 on 2024-09-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_payment_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
