# Generated by Django 4.2.16 on 2024-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_student_id_alter_teacher_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
