# Generated by Django 4.2.16 on 2024-09-29 20:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_teacher_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="syllabus_subject",
        ),
        migrations.AddField(
            model_name="course",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kcb", "Kenya Commercial Bank (KCB)"),
                    ("equity", "Equity Bank"),
                    ("cooperative", "Co-operative Bank"),
                    ("absa", "ABSA Bank Kenya"),
                    ("stanbic", "Stanbic Bank"),
                    ("nbk", "National Bank of Kenya"),
                    ("dtb", "Diamond Trust Bank"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="mpesa_phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank Transfer")],
                default="mpesa",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subjects",
            field=models.ManyToManyField(related_name="courses", to="core.subject"),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kcb", "Kenya Commercial Bank (KCB)"),
                    ("equity", "Equity Bank"),
                    ("cooperative", "Co-operative Bank"),
                    ("absa", "ABSA Bank Kenya"),
                    ("stanbic", "Stanbic Bank"),
                    ("nbk", "National Bank of Kenya"),
                    ("dtb", "Diamond Trust Bank"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="mpesa_phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank Transfer")],
                default="mpesa",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kcb", "Kenya Commercial Bank (KCB)"),
                    ("equity", "Equity Bank"),
                    ("cooperative", "Co-operative Bank"),
                    ("absa", "ABSA Bank Kenya"),
                    ("stanbic", "Stanbic Bank"),
                    ("nbk", "National Bank of Kenya"),
                    ("dtb", "Diamond Trust Bank"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="mpesa_phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank Transfer")],
                default="mpesa",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kcb", "Kenya Commercial Bank (KCB)"),
                    ("equity", "Equity Bank"),
                    ("cooperative", "Co-operative Bank"),
                    ("absa", "ABSA Bank Kenya"),
                    ("stanbic", "Stanbic Bank"),
                    ("nbk", "National Bank of Kenya"),
                    ("dtb", "Diamond Trust Bank"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="loan_deductions",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="mpesa_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="mpesa_user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="teacher",
            name="net_salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank Transfer")],
                default="exit",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="tax_deductions",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="remaining_fee",
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
