# Generated by Django 4.2.16 on 2024-09-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_course_syllabus_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("mpesa", "M-Pesa"), ("bank", "Bank Transfer")],
                default="mpesa",
                max_length=10,
            ),
        ),
    ]
