# Generated by Django 4.2.16 on 2024-09-29 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_student_results"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="bio",
        ),
    ]
