# Generated by Django 4.2.16 on 2024-09-29 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_remove_teacher_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_assigned", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "teacher")},
            },
        ),
        migrations.AddField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(
                through="core.StudentTeacher", to="core.student"
            ),
        ),
    ]
