from django.contrib import admin
from .models import Admin,Classroom,ClassStudent,StudentAssessment, Teacher, Student, Course, Payment, Subject, Qualification, Assessment, Progress, Enrollment, Message, DiscussionForumPost, Reply, Notification, Assignment, TeacherBoard, CodeEditor, CameraInteraction

admin.site.register(Admin)
admin.site.register(Teacher)
admin.site.register(Student)
admin.site.register(Course)
admin.site.register(Payment)
admin.site.register(Subject)
admin.site.register(Qualification)
admin.site.register(Assessment)
admin.site.register(Progress)
admin.site.register(Enrollment)
admin.site.register(Message)
admin.site.register(DiscussionForumPost)
admin.site.register(Reply)
admin.site.register(Notification)
admin.site.register(Assignment)
admin.site.register(TeacherBoard)
admin.site.register(CodeEditor)
admin.site.register(CameraInteraction)
admin.site.register(Classroom)
admin.site.register(ClassStudent)
admin.site.register(StudentAssessment)
# admin.site.register()
# admin.site.register()
# admin.site.register()
